name: tests-auth

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: "12.18.3"
      - run: cd auth && npm install && npm run test:ci
